# application: mrh3215
# version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app
  # script: blog_final_project.app
- url: /static
  static_dir: static

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
